Dark_theme_added
michurinn/surf-flutter-course-michurin pull request #14
Opened 2023-01-17 09:58 UTC by michurinn

2023-01-17 15:06 UTC, GeorgeOblomov commented on lib/ui/screen/sight_list_screen.dart
> +        //style: AppTypography.largeTitle,
Не нужные комментарии удаляйте.

2023-01-17 15:17 UTC, GeorgeOblomov requested changes
В целом вы с заданием справились. Но в будущем вам будет неудобно пихать все цвета в Theme. Их может оказаться очень много. Theme  мы пользуемся, когда можем задать дефолтные цвета Flutter виджетам.

Предлагаю немного улучшить. Думаю можно создать некий ThemeProvider который будет хранить состояние темы:

```dart
class ThemeProvider {
  bool isLight = true;
```  
А также разделить цвета для светлой и темной темы и хранить их в двух наследниках от BaseThem например:

```dart
class ThemeProvider {
  bool isLight = true;

  BaseTheme get appTheme => isLight ? LightTheme() : DarkTheme();

```

Таким образом можно будет устанавливать цвета таким образом:

```dart
SvgPicture.asset(
                AppAssets.filtersIcon,
                color: themeProvider.appTheme.filtersIconColor,
              ),
```              

В `main.dart` мы можем использовать его так:

```dart
import 'package:flutter/material.dart';
import 'package:places/ui/screen/res/themes.dart';
import 'package:places/ui/screen/sight_list_screen.dart';

final themeProvider = ThemeProvider();

void main() {
    
class App extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: "Surf",
      theme: themeProvider.isLighth ? lightTheme : darkTheme,
      home: const SightListScreen(),
    );
  }
```

Объект `ThemeProvider` можно пока сделать глобальным, позже когда будет тема с внедрением зависимостей, это дело поправится.

2023-01-20 18:03 UTC, michurinn commented on lib/ui/screen/sight_list_screen.dart
> +        //style: AppTypography.largeTitle,
!

2023-01-23 16:45 UTC, GeorgeOblomov approved these changes

2023-01-24 13:17 UTC, merged