4 6 2 osnovy verstki pozicionirovanie
michurinn/surf-flutter-course-michurin pull request #9
Opened 2022-11-05 20:36 UTC by michurinn

2022-11-07 14:43 UTC, GeorgeOblomov commented on lib/ui/screen/sight_details.dart
> +                width: 32,
У Container есть свойство padding, можно убрать врхний виджет Padding и переместить EdgeInsets внутрь контейнера.

2022-11-07 14:44 UTC, egrischenkov commented on lib/ui/screen/sight_details.dart
> +              child: Text(
Та же история с Padding.

2022-11-07 14:45 UTC, GeorgeOblomov commented on lib/ui/screen/sight_details.dart
> +              width: double.infinity,
А для чего здесь double.infinity?

2022-11-07 14:46 UTC, GeorgeOblomov commented on lib/ui/screen/sight_details.dart
> +}
В этом файлике нужно у всех контейнеров обернутых в Padding перенести его во внутрь.

2022-11-07 14:49 UTC, GeorgeOblomov requested changes
Не забываем пожалуйста прикладывать скриншоты, где это требуется. 
И если создаете разные PR, то не нужно дублировать изменения в каждом. В этом случае можно вливать, один PR в другой. Если изменений не очень много, можно вносить изменения в рамках одного  PR.

2022-11-07 14:50 UTC, GeorgeOblomov commented on lib/ui/screen/sight_card.dart
> +      child: SizedBox(
Здесь тоже можно объединить SizedBox с Padding, а точнее заменить их на Container

2022-11-07 14:52 UTC, GeorgeOblomov commented on lib/ui/screen/sight_card.dart
> +                        width: double.infinity,
Кажется width здесь не нужен. Это ведь просто в качестве вертикального отсупа?

2022-11-09 06:42 UTC, internetova reviewed
Надо навести порядок по комментариям:

1. Переверстать
2. Вынести стили в отдельный класс (в отдельный файл)
3. Вынести цвета в отдельный класс (в отдельный файл)
4. Строковые константы также:
```dart
/// Строковые константы приложения

class AppStrings {
  static const appTitle = 'Это тайтл';
}
```

Расставить запятые где забыли, отформатировать код.
Написать краткое описание к классам.

2022-11-09 06:42 UTC, internetova commented on lib/ui/screen/sight_card.dart
> +                      style: const TextStyle(
Предлагаю вынести все стили в отдельный класс. Сделайте в папке lib папку res и положите в нее:
```dart
class AppTypography {
  static const textText16Regular = TextStyle(
    fontSize: 16.0,
    height: 1.25,
    fontWeight: FontWeight.w400,
  );
}

2022-11-09 06:42 UTC, internetova commented on lib/ui/screen/sight_card.dart
> +                        color: Color(0xff3B3E5B),
Цвета аналогично текстовым стилям вынесите в отдельный файл:
```dart
class AppColors {
  static const myColor = Colors.red;
}

2022-11-09 06:42 UTC, internetova commented on lib/ui/screen/sight_card.dart
> +        ]),
не забываем про запятые и форматирование кода

2022-11-09 06:42 UTC, internetova commented on lib/ui/screen/sight_details.dart
> +          Container(
Тут вы использовали контейнер чтобы использовать его свойство паддинг и больше ничего. Контейнер тяжелый виджет, включает в себя много чего. если не нужны его свойства и можно заменить более легковесным виджетом, то лучше заменить. В вашем случае контейнер не нужен, используйте падинг.

2022-11-09 06:42 UTC, internetova commented on lib/ui/screen/sight_details.dart
> +                padding: const EdgeInsets.symmetric(horizontal: 16.0),
Я смотрю, вы несколько раз используете паддинг с одинаковым отступом. В этом случае лучше завернуть колонку в падинг, а не каждый виджет внутри колонки.

2022-11-09 06:42 UTC, internetova commented on lib/ui/screen/sight_list_screen.dart
> +            SightCard(sight: mocks[0]),
Преобразование списка в список виджетов:
https://www.youtube.com/watch?v=HONQFJHBfCE&t=1008s

Основные методы работы с коллекциями
https://youtu.be/W-gIKcS_hQA

2022-11-09 06:42 UTC, internetova commented on lib/ui/screen/sight_list_screen.dart
> +          false, // Чтобы содержимое Scaffold не смещалось при изменении размера екрана (например, при появлении клавиатуры)
можно убрать если не надо

2022-11-12 12:15 UTC, GeorgeOblomov approved these changes

2023-01-17 09:37 UTC, merged